### ISSUE TITLE
will there some code available for charge point service? 

### ISSUE THREAD

**Issue by ReubenBorrison** [heroyooki/ocpp-fastapi-vue3#3]

**Comment by ReubenBorrison** [comment]
I'm sorry for the empty description. I wanted to learn about how the events are being forwarded from the charge point service to the CSMS. but I was not able to find the code for it. I see that it is available as a docker image. Can someone please point me to the code for the same?

**Comment by heroyooki** [comment]
No problem. Ping me on e-mail and I gonna reply with the access token to the repo with the code.
heroyooki@gmail.com
