### ISSUE TITLE
 No module named 'pyocpp_contrib'

### ISSUE THREAD

**Issue by Arianshh** [heroyooki/ocpp-fastapi-vue3#5]
I tried to run the project step by step and I got the following error on the python server. Is this a private python package?
Thanks in advance

**Comment by heroyooki** [comment]
I gonna make those repo available on demand, in a while.

**Comment by feri27** [comment]
Hi , I also didn't find this package, can you share, your project is really awesome

**Comment by AdrielGraminho** [comment]
can you share with me this repository?

**Comment by heroyooki** [comment]
> can you share with me this repository?

not now
